version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11.4-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  tornado:
    build:
      context: .
      dockerfile: backend/dockerfile
    restart: always

    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    command: bash -c "python backend/tornado_web_app.py"
  fastapi:
    build:
      context: .
      dockerfile: servisdb/dockerfile
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    command: bash -c "python servisdb/app.py"

volumes:
  pgdata:
